# Site Information
title: b3nguang
description: "一个喜欢开源和折腾的工程师"
url: https://b3nguang.github.io
repo: b3nguang/b3nguang.github.io
lang: zh-CN
timezone: Africa/El_Aaiun

# Social Media and External URLs
github: b3nguang
menu:
  - title: "Categories"
    url: "/categories.html"
  - title: "About"
    url: "/about.html"
  - title: "Weekly"
    url: "https://weekly.b3nguang.top/"

# Build Settings
paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
future: true
highlighter: rouge
markdown: kramdown
permalink: /:year-:month-:day/:title.html
sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:year-:month-:day/:title.html
  posts_en:
    output: true
    permalink: /en/:year-:month-:day/:title.html
    sort_by: date

include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE",
    "package.json",
    "node_modules",
  ]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-sitemap
  - jekyll-feed

# Custom Site Settings
showBuyCoffee: true
payImage: //b3nguang.oss-cn-hangzhou.aliyuncs.com/static/logo.png
assetUrl: //b3nguang.github.io/images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
